apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: yu6h51zqt-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: yu6h51zqt-go 
  name: yu6h51zqt-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: yu6h51zqt-go 
